spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sharedoc
    driver-class-name: org.postgresql.Driver
    username: sharedoc_user
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
cloud:
  aws:
    s3:
      bucket: share-doc-file-storage
    credentials:
      access-key: AKIAXQJCXQXHX2BLJUFM
      secret-key: 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
    region:
      static: ap-south-1